changelog:
  categories:
    - title: C++ API Changes
      labels:
        - break cpp
    - title: New Features
      labels:
        - feature
    - title: Bug Fixes, Performance Improvements and Refactors
      labels:
        - bug fix
        - refactor
        - performance
    - title: Other Changes
      labels:
        - '*'
