from pathlib import Path

import pytest
import uproot

import uproot_custom

br_primitive = [
    "/tree:branch/m_bool",
    "/tree:branch/m_char",
    "/tree:branch/m_schar",
    "/tree:branch/m_uchar",
    "/tree:branch/m_short",
    "/tree:branch/m_sshort",
    "/tree:branch/m_ushort",
    "/tree:branch/m_int",
    "/tree:branch/m_sint",
    "/tree:branch/m_uint",
    "/tree:branch/m_long",
    "/tree:branch/m_slong",
    "/tree:branch/m_ulong",
    "/tree:branch/m_llong",
    "/tree:branch/m_sllong",
    "/tree:branch/m_ullong",
    "/tree:branch/m_float",
    "/tree:branch/m_double",
    "/tree:branch/m_ldouble",
    "/tree:branch/m_int8",
    "/tree:branch/m_uint8",
    "/tree:branch/m_int16",
    "/tree:branch/m_uint16",
    "/tree:branch/m_int32",
    "/tree:branch/m_uint32",
    "/tree:branch/m_int64",
    "/tree:branch/m_uint64",
    "/tree:branch/m_rt_bool",
    "/tree:branch/m_rt_char",
    "/tree:branch/m_rt_uchar",
    "/tree:branch/m_rt_short",
    "/tree:branch/m_rt_ushort",
    "/tree:branch/m_rt_int",
    "/tree:branch/m_rt_uint",
    "/tree:branch/m_rt_long",
    "/tree:branch/m_rt_ulong",
    "/tree:branch/m_rt_llong",
    "/tree:branch/m_rt_ullong",
    "/tree:branch/m_rt_float",
    "/tree:branch/m_rt_double",
    "/tree:branch/m_rt_ldouble",
]

br_stl_string = [
    "/tree:branch/m_str",
]

br_stl_sequence = [
    "/tree:branch/m_vec_double",
    "/tree:branch/m_set_double",
    "/tree:branch/m_list_double",
    "/tree:branch/m_uset_double",
    "/tree:branch/m_mset_double",
    "/tree:branch/m_umset_double",
    "/tree:branch/m_vec_str",
    "/tree:branch/m_vec_tstr",
]

br_stl_map = [
    "/tree:branch/m_map_int_double/m_map_int_double.first",
    "/tree:branch/m_map_int_double/m_map_int_double.second",
    "/tree:branch/m_umap_int_double/m_umap_int_double.first",
    "/tree:branch/m_umap_int_double/m_umap_int_double.second",
    "/tree:branch/m_mmap_int_double/m_mmap_int_double.first",
    "/tree:branch/m_mmap_int_double/m_mmap_int_double.second",
    "/tree:branch/m_ummap_int_double/m_ummap_int_double.first",
    "/tree:branch/m_ummap_int_double/m_ummap_int_double.second",
    "/tree:branch/m_map_str_tstr/m_map_str_tstr.first",
    "/tree:branch/m_map_str_tstr/m_map_str_tstr.second",
]

br_root_objects = [
    "/tree:branch/m_TString",
    "/tree:branch/m_TArrayC",
    "/tree:branch/m_TArrayD",
    "/tree:branch/m_TArrayF",
    "/tree:branch/m_TArrayI",
    "/tree:branch/m_TArrayL",
    "/tree:branch/m_TArrayL64",
    "/tree:branch/m_TArrayS",
]

br_cstyle_array = [
    "/tree:branch/m_bool[3]",
    "/tree:branch/m_schar[3]",
    "/tree:branch/m_int[2][3][4]",
    "/tree:branch/m_str[3]",
    "/tree:branch/m_vec_double[3]",
    "/tree:branch/m_map_int_double[3]",
    "/tree:branch/m_map_str_str[3]",
    "/tree:branch/m_tstr[3]",
    "/tree:branch/m_tarr_int[3]",
    "/tree:branch/m_simple_obj[3]",
]

br_stl_array = [
    "/tree:branch/m_arr_bool[3]",
    "/tree:branch/m_arr_schar[3]",
    "/tree:branch/m_arr_int[3]",
    "/tree:branch/m_arr_str[3]",
    "/tree:branch/m_arr_vec_int[3]",
    "/tree:branch/m_arr_map_int_double[3]",
    "/tree:branch/m_arr_map_str_str[3]",
    "/tree:branch/m_arr_tstr[3]",
    "/tree:branch/m_arr_tarr_int[3]",
]

br_stl_seq_with_obj = [
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_bool",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_char",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_schar",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_uchar",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_short",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_sshort",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_ushort",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_int",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_sint",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_uint",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_long",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_slong",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_ulong",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_llong",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_sllong",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_ullong",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_float",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_double",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_ldouble",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_int8",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_uint8",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_int16",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_uint16",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_int32",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_uint32",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_int64",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_uint64",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_rt_bool",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_rt_char",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_rt_uchar",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_rt_short",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_rt_ushort",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_rt_int",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_rt_uint",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_rt_long",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_rt_ulong",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_rt_llong",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_rt_ullong",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_rt_float",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_rt_double",
    "/tree:branch/m_vec_basic_types/m_vec_basic_types.m_rt_ldouble",
    "/tree:branch/m_vec_stl_string/m_vec_stl_string.m_str",
    "/tree:branch/m_vec_stl_sequence/m_vec_stl_sequence.m_vec_double",
    "/tree:branch/m_vec_stl_sequence/m_vec_stl_sequence.m_set_double",
    "/tree:branch/m_vec_stl_sequence/m_vec_stl_sequence.m_list_double",
    "/tree:branch/m_vec_stl_sequence/m_vec_stl_sequence.m_uset_double",
    "/tree:branch/m_vec_stl_sequence/m_vec_stl_sequence.m_mset_double",
    "/tree:branch/m_vec_stl_sequence/m_vec_stl_sequence.m_umset_double",
    "/tree:branch/m_vec_stl_sequence/m_vec_stl_sequence.m_vec_str",
    "/tree:branch/m_vec_stl_sequence/m_vec_stl_sequence.m_vec_tstr",
    "/tree:branch/m_vec_stl_map/m_vec_stl_map.m_map_int_double",
    "/tree:branch/m_vec_stl_map/m_vec_stl_map.m_umap_int_double",
    "/tree:branch/m_vec_stl_map/m_vec_stl_map.m_mmap_int_double",
    "/tree:branch/m_vec_stl_map/m_vec_stl_map.m_ummap_int_double",
    "/tree:branch/m_vec_stl_map/m_vec_stl_map.m_map_str_tstr",
    "/tree:branch/m_vec_root_objects/m_vec_root_objects.m_TString",
    "/tree:branch/m_vec_root_objects/m_vec_root_objects.m_TArrayC",
    "/tree:branch/m_vec_root_objects/m_vec_root_objects.m_TArrayD",
    "/tree:branch/m_vec_root_objects/m_vec_root_objects.m_TArrayF",
    "/tree:branch/m_vec_root_objects/m_vec_root_objects.m_TArrayI",
    "/tree:branch/m_vec_root_objects/m_vec_root_objects.m_TArrayL",
    "/tree:branch/m_vec_root_objects/m_vec_root_objects.m_TArrayL64",
    "/tree:branch/m_vec_root_objects/m_vec_root_objects.m_TArrayS",
    "/tree:branch/m_vec_cstyle_array/m_vec_cstyle_array.m_bool[3]",
    "/tree:branch/m_vec_cstyle_array/m_vec_cstyle_array.m_schar[3]",
    "/tree:branch/m_vec_cstyle_array/m_vec_cstyle_array.m_int[2][3][4]",
    "/tree:branch/m_vec_cstyle_array/m_vec_cstyle_array.m_str[3]",
    "/tree:branch/m_vec_cstyle_array/m_vec_cstyle_array.m_vec_double[3]",
    "/tree:branch/m_vec_cstyle_array/m_vec_cstyle_array.m_map_int_double[3]",
    "/tree:branch/m_vec_cstyle_array/m_vec_cstyle_array.m_map_str_str[3]",
    "/tree:branch/m_vec_cstyle_array/m_vec_cstyle_array.m_tstr[3]",
    "/tree:branch/m_vec_cstyle_array/m_vec_cstyle_array.m_tarr_int[3]",
    "/tree:branch/m_vec_cstyle_array/m_vec_cstyle_array.m_simple_obj[3]",
    "/tree:branch/m_vec_stl_array/m_vec_stl_array.m_arr_bool[3]",
    "/tree:branch/m_vec_stl_array/m_vec_stl_array.m_arr_schar[3]",
    "/tree:branch/m_vec_stl_array/m_vec_stl_array.m_arr_int[3]",
    "/tree:branch/m_vec_stl_array/m_vec_stl_array.m_arr_str[3]",
    "/tree:branch/m_vec_stl_array/m_vec_stl_array.m_arr_vec_int[3]",
    "/tree:branch/m_vec_stl_array/m_vec_stl_array.m_arr_map_int_double[3]",
    "/tree:branch/m_vec_stl_array/m_vec_stl_array.m_arr_map_str_str[3]",
    "/tree:branch/m_vec_stl_array/m_vec_stl_array.m_arr_tstr[3]",
    "/tree:branch/m_vec_stl_array/m_vec_stl_array.m_arr_tarr_int[3]",
    "/tree:branch/m_vec_simple_object/m_vec_simple_object.m_int",
    "/tree:branch/m_vec_simple_object/m_vec_simple_object.m_str",
    "/tree:branch/m_vec_simple_object/m_vec_simple_object.m_arr_int[5]",
    "/tree:branch/m_vec_simple_object/m_vec_simple_object.m_vec_double",
    "/tree:branch/m_vec_simple_object/m_vec_simple_object.m_map_int_double",
    "/tree:branch/m_vec_simple_object/m_vec_simple_object.m_map_str_str",
    "/tree:branch/m_vec_simple_object/m_vec_simple_object.m_tstr",
    "/tree:branch/m_vec_simple_object/m_vec_simple_object.m_tarr_int",
]

br_stl_map_with_obj = [
    "/tree:branch/m_map_basic_types/m_map_basic_types.first",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_bool",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_char",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_schar",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_uchar",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_short",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_sshort",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_ushort",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_int",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_sint",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_uint",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_long",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_slong",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_ulong",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_llong",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_sllong",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_ullong",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_float",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_double",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_ldouble",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_int8",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_uint8",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_int16",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_uint16",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_int32",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_uint32",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_int64",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_uint64",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_rt_bool",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_rt_char",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_rt_uchar",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_rt_short",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_rt_ushort",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_rt_int",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_rt_uint",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_rt_long",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_rt_ulong",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_rt_llong",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_rt_ullong",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_rt_float",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_rt_double",
    "/tree:branch/m_map_basic_types/m_map_basic_types.second.m_rt_ldouble",
    "/tree:branch/m_map_stl_string/m_map_stl_string.first",
    "/tree:branch/m_map_stl_string/m_map_stl_string.second.m_str",
    "/tree:branch/m_map_stl_sequence/m_map_stl_sequence.first",
    "/tree:branch/m_map_stl_sequence/m_map_stl_sequence.second.m_vec_double",
    "/tree:branch/m_map_stl_sequence/m_map_stl_sequence.second.m_set_double",
    "/tree:branch/m_map_stl_sequence/m_map_stl_sequence.second.m_list_double",
    "/tree:branch/m_map_stl_sequence/m_map_stl_sequence.second.m_uset_double",
    "/tree:branch/m_map_stl_sequence/m_map_stl_sequence.second.m_mset_double",
    "/tree:branch/m_map_stl_sequence/m_map_stl_sequence.second.m_umset_double",
    "/tree:branch/m_map_stl_sequence/m_map_stl_sequence.second.m_vec_str",
    "/tree:branch/m_map_stl_sequence/m_map_stl_sequence.second.m_vec_tstr",
    "/tree:branch/m_map_stl_map/m_map_stl_map.first",
    "/tree:branch/m_map_stl_map/m_map_stl_map.second.m_map_int_double",
    "/tree:branch/m_map_stl_map/m_map_stl_map.second.m_umap_int_double",
    "/tree:branch/m_map_stl_map/m_map_stl_map.second.m_mmap_int_double",
    "/tree:branch/m_map_stl_map/m_map_stl_map.second.m_ummap_int_double",
    "/tree:branch/m_map_stl_map/m_map_stl_map.second.m_map_str_tstr",
    "/tree:branch/m_map_root_objects/m_map_root_objects.first",
    "/tree:branch/m_map_root_objects/m_map_root_objects.second.m_TString",
    "/tree:branch/m_map_root_objects/m_map_root_objects.second.m_TArrayC",
    "/tree:branch/m_map_root_objects/m_map_root_objects.second.m_TArrayD",
    "/tree:branch/m_map_root_objects/m_map_root_objects.second.m_TArrayF",
    "/tree:branch/m_map_root_objects/m_map_root_objects.second.m_TArrayI",
    "/tree:branch/m_map_root_objects/m_map_root_objects.second.m_TArrayL",
    "/tree:branch/m_map_root_objects/m_map_root_objects.second.m_TArrayL64",
    "/tree:branch/m_map_root_objects/m_map_root_objects.second.m_TArrayS",
    "/tree:branch/m_map_cstyle_array/m_map_cstyle_array.first",
    "/tree:branch/m_map_cstyle_array/m_map_cstyle_array.second.m_bool[3]",
    "/tree:branch/m_map_cstyle_array/m_map_cstyle_array.second.m_schar[3]",
    "/tree:branch/m_map_cstyle_array/m_map_cstyle_array.second.m_int[2][3][4]",
    "/tree:branch/m_map_cstyle_array/m_map_cstyle_array.second.m_str[3]",
    "/tree:branch/m_map_cstyle_array/m_map_cstyle_array.second.m_vec_double[3]",
    "/tree:branch/m_map_cstyle_array/m_map_cstyle_array.second.m_map_int_double[3]",
    "/tree:branch/m_map_cstyle_array/m_map_cstyle_array.second.m_map_str_str[3]",
    "/tree:branch/m_map_cstyle_array/m_map_cstyle_array.second.m_tstr[3]",
    "/tree:branch/m_map_cstyle_array/m_map_cstyle_array.second.m_tarr_int[3]",
    "/tree:branch/m_map_cstyle_array/m_map_cstyle_array.second.m_simple_obj[3]",
    "/tree:branch/m_map_stl_array/m_map_stl_array.first",
    "/tree:branch/m_map_stl_array/m_map_stl_array.second.m_arr_bool[3]",
    "/tree:branch/m_map_stl_array/m_map_stl_array.second.m_arr_schar[3]",
    "/tree:branch/m_map_stl_array/m_map_stl_array.second.m_arr_int[3]",
    "/tree:branch/m_map_stl_array/m_map_stl_array.second.m_arr_str[3]",
    "/tree:branch/m_map_stl_array/m_map_stl_array.second.m_arr_vec_int[3]",
    "/tree:branch/m_map_stl_array/m_map_stl_array.second.m_arr_map_int_double[3]",
    "/tree:branch/m_map_stl_array/m_map_stl_array.second.m_arr_map_str_str[3]",
    "/tree:branch/m_map_stl_array/m_map_stl_array.second.m_arr_tstr[3]",
    "/tree:branch/m_map_stl_array/m_map_stl_array.second.m_arr_tarr_int[3]",
    "/tree:branch/m_map_simple_object/m_map_simple_object.first",
    "/tree:branch/m_map_simple_object/m_map_simple_object.second.m_int",
    "/tree:branch/m_map_simple_object/m_map_simple_object.second.m_str",
    "/tree:branch/m_map_simple_object/m_map_simple_object.second.m_arr_int[5]",
    "/tree:branch/m_map_simple_object/m_map_simple_object.second.m_vec_double",
    "/tree:branch/m_map_simple_object/m_map_simple_object.second.m_map_int_double",
    "/tree:branch/m_map_simple_object/m_map_simple_object.second.m_map_str_str",
    "/tree:branch/m_map_simple_object/m_map_simple_object.second.m_tstr",
    "/tree:branch/m_map_simple_object/m_map_simple_object.second.m_tarr_int",
]

br_stl_nested = [
    "/tree:branch/m_map3_str/m_map3_str.first",
    "/tree:branch/m_map3_str/m_map3_str.second",
    "/tree:branch/m_map_vec_obj/m_map_vec_obj.first",
    "/tree:branch/m_map_vec_obj/m_map_vec_obj.second",
    "/tree:branch/m_map_vec_str/m_map_vec_str.first",
    "/tree:branch/m_map_vec_str/m_map_vec_str.second",
]

br_stl_complicated = [
    "/tree:branch/m_vec_uset_int",
    "/tree:branch/m_carr_vec_int[5]",
    "/tree:branch/m_carr_map_int_double[5]",
    "/tree:branch/m_carr_str[5]",
    "/tree:branch/m_arr_vec_int[5]",
    "/tree:branch/m_arr_str[5]",
    "/tree:branch/m_map_vec_int/m_map_vec_int.first",
    "/tree:branch/m_map_vec_int/m_map_vec_int.second",
    "/tree:branch/m_umap_list_int/m_umap_list_int.first",
    "/tree:branch/m_umap_list_int/m_umap_list_int.second",
    "/tree:branch/m_map_set_int/m_map_set_int.first",
    "/tree:branch/m_map_set_int/m_map_set_int.second",
    "/tree:branch/m_umap_uset_int/m_umap_uset_int.first",
    "/tree:branch/m_umap_uset_int/m_umap_uset_int.second",
    "/tree:branch/m_map_vec_list_set_int/m_map_vec_list_set_int.first",
    "/tree:branch/m_map_vec_list_set_int/m_map_vec_list_set_int.second",
]

br_pointers = [
    "/tree:branch/m_vec_ptr",
]

for brs in [
    br_primitive,
    br_stl_string,
    br_stl_sequence,
    br_stl_map,
    br_root_objects,
    br_cstyle_array,
    br_stl_array,
    br_stl_seq_with_obj,
    br_stl_map_with_obj,
    br_stl_nested,
    br_stl_complicated,
    br_pointers,
]:
    uproot_custom.AsCustom.target_branches |= set(brs)


@pytest.fixture(scope="session")
def prepare_test_contexts():
    test_data_dir = Path(__file__).parent / "data"
    test_contexts = {}

    for name in [
        "primitive",
        "stl_string",
        "stl_sequence",
        "stl_map",
        "stl_array",
        "stl_seq_with_obj",
        "stl_map_with_obj",
        "stl_nested",
        "stl_complicated",
        "root_objects",
        "cstyle_array",
        "pointers",
    ]:
        test_file = uproot.open(test_data_dir / f"test_{name}.root")
        test_branches = eval(f"br_{name}")
        test_contexts[name] = {
            "file": test_file,
            "branches": test_branches,
        }

    yield test_contexts


@pytest.fixture(scope="function")
def test_contexts(prepare_test_contexts):
    for ctx in prepare_test_contexts.values():
        ctx["file"].file._array_cache = None
    return prepare_test_contexts
