"""
Type stubs for ROOT C++ reader classes.

This file contains only type hints without implementations.
"""

from uproot_custom.cpp import (
    AnyClassReader,
    AnyPointerReader,
    CStyleArrayReader,
    DoubleReader,
    EmptyReader,
    FloatReader,
    GroupReader,
    Int8Reader,
    Int16Reader,
    Int32Reader,
    Int64Reader,
    IReader,
    ObjectHeaderReader,
    STLMapReader,
    STLSeqReader,
    STLStringReader,
    TArrayCReader,
    TArrayDReader,
    TArrayFReader,
    TArrayIReader,
    TArrayLReader,
    TArraySReader,
    TObjectReader,
    TStringReader,
    UInt8Reader,
    UInt16Reader,
    UInt32Reader,
    UInt64Reader,
    read_data,
)

__all__ = [
    "AnyClassReader",
    "AnyPointerReader",
    "CStyleArrayReader",
    "DoubleReader",
    "EmptyReader",
    "FloatReader",
    "GroupReader",
    "Int8Reader",
    "Int16Reader",
    "Int32Reader",
    "Int64Reader",
    "IReader",
    "ObjectHeaderReader",
    "STLMapReader",
    "STLSeqReader",
    "STLStringReader",
    "TArrayCReader",
    "TArrayDReader",
    "TArrayFReader",
    "TArrayIReader",
    "TArrayLReader",
    "TArraySReader",
    "TObjectReader",
    "TStringReader",
    "UInt8Reader",
    "UInt16Reader",
    "UInt32Reader",
    "UInt64Reader",
    "read_data",
]
